### ISSUE TITLE
 inbox 接收到新訊息時 需要有數字通知

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#190]
capture lite inbox 顯示目前有多少待收 postcapture

**Comment by seanwu1105** [comment]
WORKAROUND: polling to get badge count.

I implemented this feature by polling because:

1. Users might ignore multiple transactions in app, and thus the `inbox_count` field does not help. App still needs to request the inbox list.
1. If the notification got pushed while the user is not using the app, the badge will never be updated as the update is outside of `ngZone`.

Ultimately, we need to apply repository pattern (see #226) to fix these problem, but I do not have additional time before the release.

See 6c5032c9807c0c8d67422981a99a0c8bf5e0a9d2.

**Comment by scott-dt** [comment]
201202 demo 會議提出將數字通知改為紅點通知

**Comment by scott-dt** [comment]
@seanwu1105 目前還是數字通知 須改為紅點顯示不要數字 ( 功能正常有正常顯示 )

**Comment by scott-dt** [comment]
beta7.3 進行測試

**Comment by scott-dt** [comment]
0.11.7 Android 於接收後會正常顯示 ios 仍有 issues 需要將 app 關閉在重啟才會顯示 #365
