### ISSUE TITLE
Can add friend and see added friends in the list

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#230]
## Description

Can add friend and see added friends in the list

**Comment by shc261392** [comment]
1. When creating a transaction, a contact invite should be created (ideally this should be included in transaction creation but somehow missed in the last release)

`POST /api/v2/contacts/invite/`
API Doc: https://dia-backend.numbersprotocol.io/redoc/#operation/api_v2_contacts_invite

The  transaction creation and contact invite creation API calls doesn't depend on each other, but it's recommended to create contact invite first, since a successful transaction creation call notifies the PostCapture receiver by email.

2. When accepting the transaction, no extra action is required.

3. Get friends

`GET /api/v2/contacts/`
API Doc:  https://dia-backend.numbersprotocol.io/redoc/#operation/api_v2_contacts_list

Example response
```
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "contact": "userA@nbs.io",
            "fake_contact_email": null,
            "created_at": "2020-12-04T08:46:52.758326Z",
            "last_updated_at": "2020-12-04T08:46:52.758365Z",
            "is_contact_since": "2020-12-04T08:46:52.790815Z",
            "state": "contact"
        }
    ]
}
```

Values of `contact` and `fake_contact_email` is mutually exclusive. A null `contact` guarantees a non-null `fake_contact_email` and vice versa.

A non-null `contact` means the contact is a real user while a non-null `fake_contact_email` means the contact only links to a email, but the email doesn't link to a real user.

The state represent the contact relationship status. Possible values all listed in the API doc.

In the current scenario, the state flow would be:

1. UserA creates a contact invite to UserB: UserA's contact state which points UserB is `request_sent`, UserB's contact state which points to UserA is `request_unread`.

2. UserB accepts the transaction sent by UserA: Both user's contact state would be `contact`.

**Comment by seanwu1105** [comment]
@shc261392 

> A non-null `contact` means the contact is a real user while a non-null `fake_contact_email` means the contact only links to a email, but the email doesn't link to a real user.

Will the contact be updated? For example, if user B accept or create the account after user A sent the contact invitation, on the next time GET `api/v2/contacts/`, will the property of `contact` and `fake_contact_email` be swapped?

**Comment by shc261392** [comment]
@seanwu1105 

> Will the contact be updated? For example, if user B accept or create the account after user A sent the contact invitation, on the next time GET api/v2/contacts/, will the property of contact and fake_contact_email be swapped?

The `contact and fake_contact_email` will be swapped when User B accepts the invitation (transaction) from User A

```
It seems POST /api/v2/contacts/invite/ is not idempotent. It will return a 403 error indicating the invite has been created before. Thus, app must check if the invitation exist or not before send the invitation. This might cause error as app needs to sync the contact atomically list first. A big catch to prevent the error throw is not an ideal solution. It would be great if you can change the API to be idempotent.
```

It should be 400 (Bad Request). POST methods in RESTful API is for non-idempotent actions since they represent server-side state changes. If the invite action is made idempotent, it would be impossible to know whether the invitation succeed or not.

Is catching only the 400 error code a viable solution? Currently all server-side validations should return 400 error.

Or there's a better solution to this: let me implement the hotfix to make sending transaction automatically creates invitation on server side.

> BTW, is there any docs for the different error codes of DIA backend APIs?

We don't use any predefined service error codes now (although we might need to later). For HTTP status code, here's the error code the backend most frequently returns:

400 (Bad Request): The request payload is malformed or not compliant with the validation rules.
403 (Forbbiden): Unauthorized. Mostly caused by not having a correct authentication header.
404 (Not Found): The requesting resource is not found or the requesting user has no permission to get.
500 (Internal Server Error): Time to ping me to fix something on the server
