### ISSUE TITLE
直接將手機 gps 關閉 會於notification 顯示 未知的錯誤 { "message":"location unavailable" } 並無法將相片存下

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#267]
## Description

直接將手機 gps 關閉 會於notification 顯示 未知的錯誤 { "message":"location unavailable" } 並無法將相片存下

## Steps to Reproduce

1. 關閉手機 gps  
2. 於app capture 頁面點選右下角 " 相機 icon " 
3. 進入相機模式
4. 按下快門 
5. 點選 " 確定 " 
6. 是否於 capture 頁面 顯示剛剛拍攝的相片

## Expected Behavior

* Expected: 1. 相片可存下 但有相關訊息顯示
                   2. 相片不存下 但要更明確地跳出訊息 ( ex: 警告無 gps 造成無法正常紀錄的字樣讓使用者清楚知道 )
* Actual: 很小的 notification 顯示 未知的錯誤 { "message":"location unavailable" }  沒有其他顯示會讓使用者覺得不能用了壞掉了的感覺

## Logs

![Screenshot_20201127-135104_Capture](https://user-images.githubusercontent.com/62582260/100426701-455b3900-30cc-11eb-9a1b-c3bf84f874fb.jpg)

## Environment

* Version: 0.8.1
* OS:, Android 10,Android 8.1.0
* Device: samsung note20  , HTC Exodus 1s

**Comment by scott-dt** [comment]
目前會顯示 正在儲存拍攝 但就不會進下一步驟 capture 頁面也沒有新的相片顯示
![Screenshot_20201204-154222_Capture](https://user-images.githubusercontent.com/62582260/101135912-78ab4400-3647-11eb-830f-4ee9f623a186.jpg)

**Comment by shc261392** [comment]
There's no technical difficulty in suppressing the error, but instead of silently collect no location data for the asset, it might be a good idea to tell the user what happens and why they won't have location data for the image.

There are 3 possible errors when collecting location data:
1. Permission Denied
2. Position Unavailable
3. Timeout

Here's a proposal to show the following snackbar:

<img width="247" alt="截圖 2020-12-07 下午5 16 02" src="https://user-images.githubusercontent.com/24616552/101332189-ee194d80-38af-11eb-8eb6-0b56da0c68bb.png">

<img width="247" alt="截圖 2020-12-07 下午5 14 57" src="https://user-images.githubusercontent.com/24616552/101332191-eeb1e400-38af-11eb-9953-d4ebbb4f5759.png">

<img width="247" alt="截圖 2020-12-07 下午5 12 38" src="https://user-images.githubusercontent.com/24616552/101332178-ea85c680-38af-11eb-933f-d7bcfabae907.png">

It shows for 4 seconds at the bottom of the screen and might blocks the Take Picture button. The downside is that if the user wants to take many pictures when location is unavailable, the user will have to wait until the snackbar dismisses after 4 seconds. Adding a manual Dismiss button is a quick solution to it.

**Comment by shc261392** [comment]
Message proposal (they are messages intended to read by users, so reviews and revisions are essential)

```
"error": {
    "locationPermissionDenied": "Location permission is denied. The relevant data will not be collected. Turn your location permission on to enable full feature of Capture.",
    "locationPositionUnavailable": "Location is not available at this moment, possibly due to weak network connectivity or GPS signals.",
    "locationTimeout": "Location info collection takes too much time, possibly due to weak network connectivity or GPS signals."
  }
```

```
"error": {
    "locationPermissionDenied": "位置存取被拒絕。相關資訊無法被蒐集。如欲使用 Capture 的完整功能，請開啟位置權限。",
    "locationPositionUnavailable": "暫時無法取得位置資訊。可能原因為網路連線或 GPS 信號不穩。",
    "locationTimeout": "取得位置資訊花費過長時間。可能原因為網路連線或 GPS 信號不穩。"
  }
```

**Comment by tammyyang** [comment]
"error": {
    "locationPermissionDenied": "Location permission is denied. Please turn your location permission on to enable the full feature of Capture app.",
    "locationPositionUnavailable": "Location is not available at this moment; possibly due to weak network connectivity or GPS signals.",
    "locationTimeout": "Location collection timeout, possibly due to weak network connectivity or GPS signals."
  }

"error": {
    "locationPermissionDenied": "位置存取被拒絕。如欲使用 Capture 的完整功能，請開啟位置權限。",
    "locationPositionUnavailable": "暫時無法取得位置資訊。可能原因為網路連線或 GPS 信號不穩。",
    "locationTimeout": "取得位置資訊花費過長。可能原因為網路連線或 GPS 信號不穩。"
  }
