### ISSUE TITLE
[bug]can't login numbers storage 

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/capture-lite#60]
## Description
can't login numbers storage .

## Steps to Reproduce

1. Go to 'setting page'
2. Scroll down to 'publisher'
3. Click on 'numbers storage'
4. Go to 'login page'
5. 狀況一 : no show email & password input box (操作10次6次會發生 )
6. 狀況二 :  show error {"non_field_errors":["unable to log in with provided credentials."}

## Expected Behavior

* Expected: can login
* Actual:狀況一 : no show email & password input box (操作10次6次會發生 )
              狀況二 :  show error {"non_field_errors":["unable to log in with provided credentials."}

## Logs
![Screenshot_20200820-110801](https://user-images.githubusercontent.com/62582260/90719485-1e2fe700-e2e7-11ea-96ad-bd669e1c2132.png)
![Screenshot_20200820-122423](https://user-images.githubusercontent.com/62582260/90719505-2851e580-e2e7-11ea-91e2-f8cfaae45be5.png)

## Environment

* Version: v0.2.0
* OS: Android 8.1.0
* Device: HTC Exodus 1_

**Comment by seanwu1105** [comment]
@scott-dt Cannot reproduce the issues.

## First Issue

> 狀況一 : no show email & password input box (操作10次6次會發生 )

![Screenshot from 2020-08-24 14-59-48](https://user-images.githubusercontent.com/14951000/91013587-7aae4180-e61a-11ea-8963-fc189db279fd.png)

The page without email and password input boxes is the main page for the Numbers Storage publisher. The page will show the user name and the email after the user has logged in.

## Second Issue

> 狀況二 : show error {"non_field_errors":["unable to log in with provided credentials."}

Please provide a set of login credentials to reproduce the error. It is possible the issue is caused by the server side.

**Comment by scott-dt** [comment]
20200824 Did not happen after signup the new account .  when i key in the wrong password will show error {"non_field_errors":["unable to log in with provided credentials."}

**Comment by scott-dt** [comment]
20200825 Second confirmation by scott
