### ISSUE TITLE
Categorize photos by creation date

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/capture-lite#95]
(WIP)
## Update Purpose

Write the purpose of UI update here.

## UI Suggestion

Put images or link to the contents of suggestions.

## More Description (if any)

Put more description here to help developers understand.

**Comment by shc261392** [comment]
Suggested implementation:

1. The feature should be imeplemented in [storage page](https://github.com/numbersprotocol/capture-lite/tree/master/src/app/pages/storage). First of all, creation dates should be derived from the [timestamp](https://github.com/numbersprotocol/capture-lite/blob/develop/src/app/services/data/proof/proof.ts#L6) of each proof. Add a `creation_date` property in the returning object (the object that will be emitted by `proofWithRaw$` ) and filled it with value converted from `timestamp`.

2. Declare another readonly observable `proofsWithRawByDate$`, use `proofsWithRaw$` as source observable, use pipable operators to convert the emitted type of source observable (an array of object) to a nested array of object where the outer array represents each unique date and the inner array represent all proofs/b64strings within the given date.

3. Modify the [template](https://github.com/numbersprotocol/capture-lite/blob/master/src/app/pages/storage/storage.page.html#L13) to use `proofsWithRawByDate$` instead of `proofsWithRaw$`, unroll the nested array to categorize photos by dates.

4. Adjust styles to meet the UI design
