### ISSUE TITLE
Add Login & Signup pages

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/capture-lite#96]
(WIP)
## Concept

If we provide \[feature]

## Reason/Hypothesis

We can help \[who] to \[benefit] or solve \[problem] because we know \[who] are \[faced about our target].

## More Description (if any)

Put more description here to support the concept.

## Suggested Implementation (if any)

Put some suggested implementation here if you already have some ideas in mind.

**Comment by CS6** [comment]
![image](https://user-images.githubusercontent.com/16307922/92718059-d35c3900-f393-11ea-8a45-8bb3ee27af07.png)

**Comment by shc261392** [comment]
1. The current account system in storage backend uses `email` as the unique identifier for users, while `username` is optional. This contradicts with the current signup/login UI design. Which one should we follow?

2. Do we need email verification? (Requesting email from user, especially using it a the unique identifier for user, without doing verification is usually a bad practice since the user might create lots of fake accounts or impose as others with the email accounts they don't own)

3. In the Signup page, there should be a way for the user to go back to Login page, because the user might suddenly remember that they do have an account or they actually get to this page by accidentally clicked the wrong button. (They should be allowed to freely go back and forth between signup/login page.)

4. Do we allow the user to use the App without successfully login? (Internet is required when first time using the App)

**Comment by shc261392** [comment]
@CS6 請幫我做以下件事情：

1. 新增兩個 page（login & signup），如 UI 設計的版面跟樣式，但有以下變更：

    - 輸入框的第一行要放 email ，而不是 username

    - Signup 頁面不需要第四行（原本是 username 的那一行）

    - Signup 頁面底下的 `SIGN UP` 按鈕底下要新增另外一個按鈕，內容寫 `ALREADY HAVE AN ACCOUNT?`

2. 先設成進入 App 時固定先顯示 login page ，接著在 `CREATE AN ACCOUNT?` `ALREADY HAVE AN ACCOUNT?` 按鈕加上 routerLink ，可以來回切換這兩個頁面。button routerLink 要設定 `replaceUrl="true"` 屬性，讓 navigation history 不會一直疊上去

3. 幫這兩個頁面所有文字套用 i18n https://github.com/numbersprotocol/capture-lite/blob/master/src/assets/i18n/en-us.json （英文即可）

如果完成的話，請 ping 我告訴我做在哪一個 branch ，先不要發 pull request

**Comment by shc261392** [comment]
@CS6 3 會用到的英文翻譯我已經更新到最新的 `develop` 了，可以直接套用 i18n ，在 `en-us.json` 中應該可以找到你需要的所有翻譯字串，如果有缺請 ping 我

**Comment by CS6** [comment]
@shc261392  請看 https://github.com/numbersprotocol/capture-lite/tree/feature-loginUI
