### ISSUE TITLE
Add Settings and drawer

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/capture-lite#97]
(WIP)
## Concept

If we provide \[feature]

## Reason/Hypothesis

We can help \[who] to \[benefit] or solve \[problem] because we know \[who] are \[faced about our target].

## More Description (if any)

Put more description here to support the concept.

## Suggested Implementation (if any)

Put some suggested implementation here if you already have some ideas in mind.

**Comment by tammyyang** [comment]
Drawer 會採用類似 Instagram 的全屏顯示 + back key

**Comment by CS6** [comment]
![image](https://user-images.githubusercontent.com/16307922/92714032-3fd43980-f38e-11ea-8b3c-519de235cdb6.png)
@tammyyang

**Comment by shc261392** [comment]
Suggested Implementation:

1. Create a shared header component with `ionic g component components/header`

2. Replace the current headers in `information`, `proof`, `settings` and `storage` page with the newly created shared header component. Use property binding and input decorator to consume variables such as header names. (See [MyLog shared header](https://github.com/MyDataTaiwan/mylog14/tree/develop/src/app/core/header) for example)

3. Add [ion-menu](https://ionicframework.com/docs/api/menu) in the header component. According to the discussion in Kick-off, both style (as shown above in the previous comment) is acceptable.

4. Add navigation events on each menu item so that the user can visit these pages with the drawer. (Pages not yet exist could be ignored)

**Comment by ethanwu155** [comment]
I think the new header component with settings drawer is only on `storage` page according to https://www.figma.com/file/XW6PCABaxTBxKlCAqH95W9/CAPTURE?node-id=240%3A1294

<img width="353" alt="Screen Shot 2020-09-16 at 5 24 35 PM" src="https://user-images.githubusercontent.com/17772957/93318740-a3081500-f841-11ea-8adb-c26a32419754.png">
<img width="353" alt="Screen Shot 2020-09-16 at 5 24 41 PM" src="https://user-images.githubusercontent.com/17772957/93318753-a6030580-f841-11ea-8dbe-113530191c12.png">
<img width="353" alt="Screen Shot 2020-09-16 at 5 24 46 PM" src="https://user-images.githubusercontent.com/17772957/93318759-a69b9c00-f841-11ea-8cd9-3384f6bf586b.png">
<img width="353" alt="Screen Shot 2020-09-16 at 5 24 53 PM" src="https://user-images.githubusercontent.com/17772957/93318761-a7343280-f841-11ea-8489-17a106cc66a6.png">
<img width="353" alt="Screen Shot 2020-09-16 at 5 24 58 PM" src="https://user-images.githubusercontent.com/17772957/93318764-a7ccc900-f841-11ea-8f5e-81e695c075ea.png">

**Comment by shc261392** [comment]
@ethanwu155 
It's like you said, so creating a shared header component would be not so relevant to this feature.

If you haven't created a shared header component, I'd suggest skipping the shared component and directly implementing the draw on storage page. If you have created it it's fine too, just use component property to determine whether or not to show the drawer icon.

**Comment by ethanwu155** [comment]
thanks for the feedback. I will submit a pull request.
